### PR TITLE
(MODULES-8892) - v0.5.0 Release Prep

### PR DESCRIPTION
**Pull request by david22swan**

### CODE REVIEW

**Comment by david22swan** [comment]
@david22swan What's the timeline on it getting merged in?? Releases are easy to do after all.

**Comment by donoghuc** [comment]
This should be ready today (ran out of time on Friday, I have a typo in Windows acceptance test). Once meged I will make sure to push commits to release branch and update the changelog.

**Comment by david22swan** [comment]
@donoghuc It's fine, I can handle that part

**Comment by donoghuc** [comment]
@david22swan waiting on a final review from @m0dular (he has a refactor of bash implementation in mind based on conversation in slack). Given the fact that we have acceptance tests green (https://jenkins-master-prod-1.delivery.puppetlabs.net/job/forge-module_puppetlabs-package_init-manual-parameters_adhoc/54/) I think it is pretty low risk to let him try to refactor in the next day or two. I propose we consider waiting to get this work in for the 0.5.0 release till no later than wednesday.

**Comment by david22swan** [comment]
@donoghuc Ok

**Comment by donoghuc** [comment]
@david22swan got everything we want in `0.5.0` merged in master. Thanks so much for waiting.

**Pull request merged**
